### PR TITLE
Finish refactoring ResponseTest

### PR DESCRIPTION
**Pull request by Serdiuk-Andrii**

### CODE REVIEW

**Review by AlekseyPanas — DISMISSED** [review]

**Review by cotopaxi64 — COMMENTED** [review]
Great work. I do have a question though, on the tests, do you think it may be necessary to include a separate test for what happens when the code FAIL is called?

**Comment by Serdiuk-Andrii** [comment]
> Great work. I do have a question though, on the tests, do you think it may be necessary to include a separate test for what happens when the code FAIL is called?

Thank you, this is a good point

**Review by bac423 — APPROVED** [review]
Amazing

**Review by AlekseyPanas — APPROVED** [review]

**Review by cotopaxi64 — APPROVED** [review]
Looks good to me.

**Pull request merged**
