### PR TITLE
106 use case get all titles

### PR DESCRIPTION
**Pull request by joel-mat-03**

### CODE REVIEW

**Review by tostistos — APPROVED** [review]
GAT. Very good

**Review by bac423 — CHANGES_REQUESTED** [review]
Please add getAllTitles method to the interactor

**Review by AlekseyPanas — APPROVED** [review]

**Review by bac423 — APPROVED** [review]
Amazing job

**Review by AlekseyPanas — APPROVED** [review]

**Review by bac423 — APPROVED** [review]
Great job

**Review by tostistos — APPROVED** [review]

**Pull request merged**
